#ESSA Conference Poster - Figure Code
##Figure 1 - Ventilation Volume
```{r}
pd<- position_dodge(width = 0.6)



SUMVE$session_f = factor(SUMVE$session, levels=c("SW", "SWBFR", "FW", "FWBFR"))
SUMVE$workingdata_f = factor(SUMVE$workingdata, levels=c("PRE_REST","PERIOD_1","PERIOD_2","PERIOD_3","PERIOD_4", "PERIOD_5", "POST_RER"))

session_f.labs<- c("Comfortable Walk", "Comfortable Walk + BFR", "Fast Walk", "Fast Walk + BFR")
 names(session_f.labs)<-c("SW","SWBFR","FW", "FWBFR")
 
 SUMVE$speed_f = factor(SUMVE$speed, levels=c("SW", "FW"))
 speed.labs<- c("Low-Intensity","Moderate-Intensity")
  names(speed.labs)<-c("SW", "FW")
  
  label.testVE_2 <- data.frame(session_f = c("FWBFR"),
                                  workingdata_f = c("PERIOD_2"),
                                 speed_f = c("FW"),
                                 VE = c(39))
  
  label.testVE_3 <- data.frame(session_f = c("FWBFR"),
                                  workingdata_f = c("PERIOD_3"),
                                 speed_f = c("FW"),
                                 VE = c(40.1))
  
  label.testVE_4 <- data.frame(session_f = c("FWBFR"),
                                  workingdata_f = c("PERIOD_4"),
                                 speed_f = c("FW"),
                                 VE = c(41.5))
  
  label.testVE_5 <- data.frame(session_f = c("FWBFR"),
                                  workingdata_f = c("PERIOD_5"),
                                 speed_f = c("FW"),
                                 VE = c(42))
 
SUMVEplot<-ggplot(SUMVE, aes(x = workingdata_f, y = VE, colour= session_f)) +
          geom_line(aes(colour = session_f, group = session_f), position = pd)+
          geom_errorbar(aes(ymin = VE-ci, ymax=VE+ci, group= session_f),width = .5,colour = "black",position= pd)+
          geom_point(aes(shape = session_f, colour = session_f),fill = "white", size = 4, stroke = 1.0, position= pd)+
          
        scale_colour_manual(name = "session_f",
                            labels = session_f.labs,
                            values = c("#FFCDD2", "#EF9A9A", "#E53935", "#C62828"))+
        scale_shape_manual(name = "session_f",
                           labels = session_f.labs,
                           values = c(22, 15, 21, 16))+
  
  facet_grid(~speed_f, labeller = labeller(speed_f = speed.labs))+
        theme(legend.position= "none")+
        xlab("\n Exercise Duration") + ylab("Minute Ventilation \n")+
        scale_x_discrete(breaks=c("PERIOD_1","PERIOD_2","PERIOD_3","PERIOD_4", "PERIOD_5"),
              labels=c("2min", "4min", "6min", "8min", "10min"))+
        theme_bw()+
        theme(legend.position= "")+
        
      theme(axis.line = element_line(colour = "black", size = 0.4, linetype = "solid"),
                  axis.text.x=element_text(size=16, colour="black"),
                  axis.text.y=element_text(size=16, colour="black"))+
      theme(axis.text.x=element_text(size=16, angle = 0),
                   axis.title.x=element_text(size=18),
                   axis.title.y=element_text(size=18),
                   strip.text.y=element_text(size=14,face="italic"),
                   strip.text.x=element_text(size=14,face="italic"),
                   legend.title = element_blank())+
                   
  geom_text(data = label.testVE_2, label = "         a", position = pd)+
  geom_text(data = label.testVE_3, label = "         a", position = pd)+
  geom_text(data = label.testVE_4, label = "         a", position = pd)+
  geom_text(data = label.testVE_5, label = "         a", position = pd)
        
        
SUMVEplot
```

```{r}
ggsave(plot=SUMVEplot,"C:\\Users\\thoma\\OneDrive - Murdoch University\\Desktop\\PhD 2020\\Conferences\\ESSA\\WALK STUDY\\VE(ESSA Poster-Colour).png",units = "in",width = 15.0,height = 9.0)
```

##Figure 2 - Heart Rate
```{r}
pd<- position_dodge(width = 0.8)

SUMchp1hr$session_f = factor(SUMchp1hr$session, levels=c("SW","SWBFR","FW", "FWBFR", "JOG"))
SUMchp1hr$workingdata_f = factor(SUMchp1hr$workingdata, levels=c("PRE_REST","PERIOD_1","PERIOD_2","PERIOD_3","PERIOD_4", "PERIOD_5"))

 session_f.labs<- c("Low-Intensity", "Low-Intensity + BFR", "Moderate-Intensity", "Moderate-Intensity + BFR", "Vigorous-Intensity")
 names(session_f.labs)<-c("SW","SWBFR","FW", "FWBFR", "JOG")
 
  SUMchp1hr$speed_f = factor(SUMchp1hr$speed, levels=c("SW", "FW"))
 speed.labs<- c("Low-Intensity","Moderate-Intensity")
  names(speed.labs)<-c("SW", "FW")
  
  label.testHR_2 <- data.frame(session_f = c("FWBFR"),
                                  workingdata_f = c("PERIOD_2"),
                                 speed_f = c("FW"),
                                 HR..bpm. = c(140))
  
  label.testHR_3 <- data.frame(session_f = c("FWBFR"),
                                  workingdata_f = c("PERIOD_3"),
                                 speed_f = c("FW"),
                                 HR..bpm. = c(145))
  
  label.testHR_4 <- data.frame(session_f = c("FWBFR"),
                                  workingdata_f = c("PERIOD_4"),
                                 speed_f = c("FW"),
                                 HR..bpm. = c(149))
  
  label.testHR_5 <- data.frame(session_f = c("FWBFR"),
                                  workingdata_f = c("PERIOD_5"),
                                 speed_f = c("FW"),
                                 HR..bpm. = c(150))
  
  label.testHRsw_1 <- data.frame(session_f = c("SWBFR"),
                                 workingdata_f = c("PERIOD_1"),
                                 speed_f = c("SW"),
                                 HR..bpm. = c(130))
  
  label.testHRsw_2 <- data.frame(session_f = c("SWBFR"),
                                  workingdata_f = c("PERIOD_2"),
                                 speed_f = c("SW"),
                                 HR..bpm. = c(127))
  
  label.testHRsw_3 <- data.frame(session_f = c("SWBFR"),
                                  workingdata_f = c("PERIOD_3"),
                                 speed_f = c("SW"),
                                 HR..bpm. = c(126))
  
  label.testHRsw_4 <- data.frame(session_f = c("SWBFR"),
                                  workingdata_f = c("PERIOD_4"),
                                 speed_f = c("SW"),
                                 HR..bpm. = c(128))
  
  label.testHRsw_5 <- data.frame(session_f = c("SWBFR"),
                                  workingdata_f = c("PERIOD_5"),
                                 speed_f = c("SW"),
                                 HR..bpm. = c(131))


chp1HRplot<-ggplot(SUMchp1hr, aes(x = workingdata_f, y = HR..bpm., colour= session_f)) +
          geom_line(aes(group = session_f, colour = session_f), position = pd)+
          geom_errorbar(aes(ymin = HR..bpm.-ci, ymax=HR..bpm.+ci, group= session_f),colour = "black",position= pd)+
          geom_point(aes(shape = session_f, colour = session_f), fill = "white", size = 4, stroke = 1.0, position= pd)+
                  scale_colour_manual(name = "session_f",
                            labels = session_f.labs,
                            values = c("#FFCDD2", "#EF9A9A", "#E53935", "#C62828"))+
                  scale_shape_manual(name = "session_f",
                           labels = session_f.labs,
                           values = c(22, 15, 21, 16))+
        theme_bw()+
        theme(legend.position= "")+
        xlab("\n Exercise Duration") + ylab("Heart Rate (beats/min) \n")+
         scale_x_discrete(breaks=c("PERIOD_1","PERIOD_2","PERIOD_3","PERIOD_4", "PERIOD_5"),
              labels=c("2min", "4min", "6min", "8min", "10min"))+
        facet_grid(~speed_f, labeller = labeller(speed_f = speed.labs))+ 
        theme(legend.position= "")+
        
         theme(axis.line = element_line(colour = "black", size = 0.4, linetype = "solid"),
                  axis.text.x=element_text(size=16, colour="black"),
                  axis.text.y=element_text(size=16, colour="black"))+
         theme(axis.text.x=element_text(size=16, angle = 0),
                   axis.title.x=element_text(size=18),
                   axis.title.y=element_text(size=18),
                   strip.text.y=element_text(size=14,face="italic"),
                   strip.text.x=element_text(size=14,face="italic"),
                   legend.title = element_blank())+
                   geom_text(data = label.testHR_2, label = "             a")+
                   geom_text(data = label.testHR_3, label = "             a")+
                   geom_text(data = label.testHR_4, label = "             a")+
                   geom_text(data = label.testHR_5, label = "             a")+
                   geom_text(data = label.testHRsw_1, label = "            a")+
                   geom_text(data = label.testHRsw_2, label = "            a")+
                   geom_text(data = label.testHRsw_3, label = "            a")+
                   geom_text(data = label.testHRsw_4, label = "            a")+
                   geom_text(data = label.testHRsw_5, label = "            a")
                        

chp1HRplot
```

```{r}
ggsave(plot=chp1HRplot,"C:\\Users\\thoma\\OneDrive - Murdoch University\\Desktop\\PhD 2020\\Conferences\\ESSA\\WALK STUDY\\HR(ESSA Poster-Colour).png",units = "in",width = 15.0,height = 9)
```

##Figure 3a - Sessional RPE
```{r}
sRPEmeans$session_f = factor(sRPEmeans$session, levels=c("SW","SWBFR","FW", "FWBFR", "JOG"))
 session_f.labs<- c("Comfortable Walk", "Comfortable Walk + BFR", "Fast Walk", "Fast Walk + BFR", "Jogging")
 
 names(session_f.labs)<-c("SW","SWBFR","FW", "FWBFR", "JOG")
 
  label.testsRPE_1 <- data.frame(session_f = c("FWBFR"),
                                           sRPE = c(6.5))
  
  label.testsRPE_2 <- data.frame(session_f = c("SWBFR"),
                                         sRPE = c(4.5))
  
  label.testsRPE_3 <- data.frame(session_f = c("FW"),
                                         sRPE = c(4.5))
 
 sRPEPLOT <- ggplot(sRPEmeans,aes(x=session_f, y=sRPE))+
        geom_errorbar(aes(ymin = sRPE-ci, ymax=sRPE+ci, group= session_f),colour = "black",position= pd)+   
     geom_col(aes(fill = session_f, group = session_f),position = pd1)+
     theme_bw()+
     scale_fill_manual(name = "session_f",
                            labels = session_f.labs,
                            values = c("#FFCDD2", "#EF9A9A", "#E53935", "#C62828"))+
     
   theme(legend.position= "")+
   xlab("") + ylab("Rating of Perceived Exertion")+
        
   scale_y_continuous(breaks = c(0,1,2,3,4,5,6,7,8,9,10), limits = c(0,10))+
   
   theme(axis.line = element_line(colour = "black", size = 0.4, linetype = "solid"),
         axis.text.x=element_blank(),
         axis.ticks.x = element_blank(),
         axis.text.y=element_text(size=16, colour="black"))+
   theme(axis.title.x=element_text(size=18),
         axis.title.y=element_text(size=18),
         strip.text.y=element_text(size=14,face="italic"),
         strip.text.x=element_text(size=14,face="italic"),
         legend.title = element_blank())+
                   
   geom_text(data = label.testsRPE_1, label = " b", position = pd)+
   geom_text(data = label.testsRPE_2, label = " c", position = pd)+
   geom_text(data = label.testsRPE_3, label = " d", position = pd)


        
 
 sRPEPLOT
            
```

```{r}
ggsave(plot=sRPEPLOT,"C:\\Users\\thoma\\OneDrive - Murdoch University\\Desktop\\PhD 2020\\Conferences\\ESSA\\WALK STUDY\\sRPE(ESSA Poster).png",units = "in",width = 15.0,height = 11.0)
```

##Figure 3b - Sessional Discomfort

```{r}
RPDmeans <- AAA_RPEBIND%>%
  summarySE(measurevar = "RPD", groupvar =c("session"), na.rm = TRUE, conf.interval = 0.95, .drop = TRUE)%>%
filter(!session %in% "JOG")
```


```{r}
RPDmeans$session_f = factor(RPDmeans$session, levels=c("SW","SWBFR","FW", "FWBFR", "JOG"))

  label.testsRPD_1 <- data.frame(session_f = c("FWBFR"),
                                           RPD = c(6.5))
  
  label.testsRPD_2 <- data.frame(session_f = c("SWBFR"),
                                         RPD = c(4.7))
  
  label.testsRPD_3 <- data.frame(session_f = c("FW"),
                                         RPD = c(3))



 session_f.labs<- c("Comfortable Walk", "Comfortable Walk + BFR", "Fast Walk", "Fast Walk + BFR", "Jogging")
 names(session_f.labs)<-c("SW","SWBFR","FW", "FWBFR", "JOG")
 RPDPLOT <- ggplot(RPDmeans,aes(x=session_f, y=RPD))+
   geom_errorbar(aes(ymin = pmax(RPD-ci, 0.05), ymax=RPD+ci, group= session_f),colour = "black",position= pd1)+         
   geom_col(aes(fill = session_f, group = session_f),position = pd1)+
   
   scale_fill_manual(name = "session_f",
                            labels = session_f.labs,
                            values = c("#FFCDD2", "#EF9A9A", "#E53935", "#C62828"))+
   
   theme_bw()+
   theme(legend.position= "")+
   xlab("") + ylab("Limb Discomfort")+
        
   scale_y_continuous(breaks = c(0,1,2,3,4,5,6,7,8,9,10), limits = c(0,10))+
   
   theme(axis.line = element_line(colour = "black", size = 0.4, linetype = "solid"),
         axis.text.x=element_blank(),
         axis.ticks.x = element_blank(),
         axis.text.y=element_text(size=16, colour="black"))+
   theme(axis.title.x=element_text(size=18),
         axis.title.y=element_text(size=18),
         strip.text.y=element_text(size=14,face="italic"),
         strip.text.x=element_text(size=14,face="italic"),
         legend.title = element_blank())+
        
   geom_text(data = label.testsRPD_1, label = " b", position = pd)+
   geom_text(data = label.testsRPD_2, label = " c", position = pd)+
   geom_text(data = label.testsRPD_3, label = " d", position = pd)
            
RPDPLOT
```

```{r}
SUBFIG <- ggarrange(sRPEPLOT,RPDPLOT, labels=c("A", "B"), ncol=1, nrow=2, common.legend = TRUE, legend = "none")

SUBFIG
```

```{r}
ggsave(plot=SUBFIG,"C:\\Users\\thoma\\OneDrive - Murdoch University\\Desktop\\PhD 2020\\Conferences\\ESSA\\WALK STUDY\\SUBFIG-COLOUR(ESSA Poster).png",units = "in",width = 15.0,height = 9.0)
```

